#*********************************************************************************
# content      = user configuration data
#
# version      = 0.1.0
# date         = 2019-10-01
# 
# how to       =
# dependencies =
# todos        =
#
# license      =
# author       = Alexander Richter <alexanderrichtertd.com>
# 
#**********************************************************************************

#**********************************************************************************
# GENERAL
#**********************************************************************************

name: Maya Tool Manager


#**********************************************************************************
# POPUP FUNCTIONS (booleans YES and NO need quotation to become str type)
#**********************************************************************************

general_warning:
    # basic info (popup_functions module)
    button:
        - GOT IT
        - CANCEL
        - HELP
    
    icon:
        warning
    
    defaultButton:
        'YES'

    cancelButton:
        'NO'

    dismissString:
        'NO'

    messageAlign:
        center

    backgroundColor:
        - 0.80
        - 0.58
        - 0.00

    # id check popup
    title:
        ID CHECK POPUP WINDOW (missing directory)
    
    # main check popup
    title:
        MAIN SCRIPT WINDOW (missing file)

